/**
 * packages/server/src/middleware/authenticate.ts
 */

import { Request, Response, NextFunction } from 'express';
import { AppError } from './errorHandler';
import { decodeToken } from '../utils/crypto';

export interface AuthenticatedRequest extends Request {
  user?: { id: string };
}

export function authenticate(
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction,
): void {
  const header = req.headers?.authorization;

  if (!header || !header.startsWith('Bearer ')) {
    return next(new AppError('Unauthorized', 401));
  }

  const token = header.slice(7);

  if (!token || token === 'invalid') {
    return next(new AppError('Unauthorized', 401));
  }

  // Decode the token generated by generateToken() in crypto.ts.
  // Replaces the previous stub that hard-coded 'user-1' for every request,
  // which allowed any valid-looking Bearer token to masquerade as that user.
  const decoded = decodeToken(token);
  if (!decoded || !decoded.userId) {
    return next(new AppError('Unauthorized', 401));
  }

  req.user = { id: decoded.userId };
  next();
}